Implmenting `ANSIBLE_DRY_RUN`
bitops-plugins/ansible pull request #10
Opened 2023-02-06 17:16 UTC by PhillypHenning

fixes https://github.com/bitops-plugins/ansible/issues/9

# Logs
```
[Bitovi] [ansible] $ ./test.sh                  
+ PLAYBOOK=main.yaml
+ ANSIBLE_ARGS='--inventory inventory.ini'
+ [[ -n '' ]]
+ echo 'Running playbook. [ansible-playbook main.yaml --inventory inventory.ini]'
Running playbook. [ansible-playbook main.yaml --inventory inventory.ini]
[Bitovi] [ansible] $ export BITOPS_ANSIBLE_DRYRUN=true; ./test.sh 
+ PLAYBOOK=main.yaml
+ ANSIBLE_ARGS='--inventory inventory.ini'
+ [[ -n true ]]
+ ANSIBLE_ARGS='--inventory inventory.ini --check'
+ echo 'Running playbook. [ansible-playbook main.yaml --inventory inventory.ini --check]'
Running playbook. [ansible-playbook main.yaml --inventory inventory.ini --check]

```

2023-02-06 21:20 UTC, arm4b requested changes
Digging deeper, looks like we have more problems with the approach overall and schema.

Let's postpone this PR for a while, I'll try to dig into the BitOps core.

2023-02-06 21:20 UTC, arm4b commented on scripts/ansible_install_playbooks.sh
> +    ANSIBLE_ARGS="$ANSIBLE_ARGS --check" # DRY RUN
Thanks for composing a PR!

I was also looking at `extra-vars` which is also not implemented in the https://github.com/bitovi/github-actions-deploy-stackstorm/pull/49, dug deeper, and realized that we might have a bigger problem.

The BitOps core should be composing a full CLI based on the config schema.

This is relevant to a higher-level issue: [CLI args to the plugins are not passed #360](https://github.com/bitovi/bitops/issues/360)

2023-02-06 21:20 UTC, arm4b commented on scripts/ansible_install_playbooks.sh
> +    ANSIBLE_ARGS="$ANSIBLE_ARGS --check" # DRY RUN
In other words, we can't add a manual bash logic for every single setting in the schema, - it'll be a never-ending game and not scalable.
Instead of doing something like this:

https://github.com/bitops-plugins/ansible/blob/bb1c588fc98a1429bc500c8546e9e15ff3928227/deploy.sh#L37-L40
https://github.com/bitops-plugins/ansible/blob/75058a7dba4c7b9644cf65251e59faa3bb9faaf8/bitops.schema.yaml#L23-L26

the user should be able to add a new setting in the schema and that'll be generating a CLI in BitOps core that's passed to the plugin execution. With the additional ENV var exported, the user can also potentially add extra logic to the plugin like we're doing.

Were there any discussions about this?

2023-02-07 15:27 UTC, PhillypHenning commented on scripts/ansible_install_playbooks.sh
> +    ANSIBLE_ARGS="$ANSIBLE_ARGS --check" # DRY RUN
There is no discussion around this that I'm aware of.
I'm not 100% confident I understand, would love more details on this

2023-02-07 16:55 UTC, arm4b commented on scripts/ansible_install_playbooks.sh
> +    ANSIBLE_ARGS="$ANSIBLE_ARGS --check" # DRY RUN
See https://github.com/bitovi/bitops/issues/360 there's a whole issue of missing implementation.

Most recent explanation here: https://github.com/bitovi/bitops/issues/360#issuecomment-1421099192

2023-02-17 17:05 UTC, closed without merging